rental_project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('src.urls' , namespace='src'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/urls.py
from django.urls import path 
from .views import *

app_name = 'src'

urlpatterns = [
    path('' , home , name="home") ,
    path('user-login/' , user_login , name="login") ,
    path('user-logout/' ,user_logout , name="logout") ,
    path('seller-register/' , seller_register , name="seller-register") ,    
    path('seller-dashboard/' , seller_dashboard , name="seller-dashboard") ,
    path('booked-yacht/' , booked_yacht , name="booked-yacht") ,
    path('add-yacht/'  , add_yacht , name="add-yacht")  ,
    path('customer-register/' , customer_register , name="customer-register") ,
    path('yacht-form/<int:pk>/' , yacht_form , name="yacht-form") ,
    path('customer-profile/' , customer_profile , name="customer-profile") ,
    
]

src/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



############################ SELLLER ######################################################
class seller(models.Model):
    user    = models.ForeignKey(User , on_delete=models.CASCADE)
    name    = models.CharField(max_length=50)
    phone   = models.CharField(max_length=20 , null=True , blank=True)
    address = models.CharField(max_length=20 , null=True , blank=True)


    def __str__(self):
        return self.name
sizes = (
    ('24' ,'24 meters') ,
    ('80' , '80 meters')
)


class yacht_details(models.Model):
    seller_id               = models.ForeignKey(seller , on_delete=models.CASCADE)
    yacht_type              = models.CharField(max_length=100)
    yacht_sizes             = models.CharField(max_length=50)
    yacht_style_categories  = models.CharField(max_length=100)
    rent_price              = models.BigIntegerField(default=0)
    yacht_image             = models.ImageField(upload_to="Yacht Images")

    def __str__(self):
        return  self.seller_id.name



############################ CUSTOMER ######################################################

class customer(models.Model):
    user        = models.ForeignKey(User , on_delete=models.CASCADE)
    name        = models.CharField(max_length=50)
    phone       = models.CharField(max_length=20 , null=True , blank=True)
    address     = models.CharField(max_length=20 , null=True , blank=True)
    price_range = models.IntegerField(default=0)


class book_yatch(models.Model):
    yacht_details_id = models.ForeignKey(yacht_details , on_delete=models.CASCADE)
    customer_id      = models.ForeignKey(customer , on_delete=models.CASCADE)
    rent_weeks       = models.CharField(max_length=50)
    price            = models.BigIntegerField(default=0)

src/forms.py
from django import forms
from .models import *


class yacht_detailsForm(forms.ModelForm):
    class Meta:
        model   = yacht_details
        fields  = (
            "yacht_type",
            "yacht_sizes",
            "yacht_style_categories",
            "rent_price",
            "yacht_image"
        )

src/views.py
from django.shortcuts import render , redirect
from django.contrib import messages
from django.contrib.auth import authenticate,logout as deauth, login  as dj_login
from .models import *
from django.conf import settings 
from django.core.mail import send_mail
from .forms import yacht_detailsForm
from django.template.loader import render_to_string
# Create your views here.



def home(request):
    yachtes=yacht_details.objects.all()
    context={
        'yachtes':yachtes
    }
    if request.user.is_authenticated:
        is_seller = False
        is_customer = False
        get_seller=seller.objects.filter(user=request.user)
        get_customer= customer.objects.filter(user=request.user)

        if get_seller:
            is_seller = True
        if get_customer:
            is_customer = True
        context={
            'yachtes':yachtes,
            'seller':is_seller ,
            'customer':is_customer
        }    
    return render(request , 'home.html',  context)

def user_login(request):
    if request.POST:
        get_email = request.POST.get('username')
        get_pass = request.POST.get('password1')

        if User.objects.filter(username=get_email).exists():
            user = authenticate(username=get_email , password=get_pass)
            if user:
                dj_login(request , user)
                messages.success(request , 'Logged in successfully')
                return redirect('src:home')
            else:
                messages.success(request , 'please enter correct password')
                return redirect('src:login')
        else:
            messages.success(request , 'This email is not registerd or incorrect')
            return redirect('src:login')

    return render(request , 'login.html')

def seller_register(request):
    if request.POST:
        get_email = request.POST.get('username')
        get_name = request.POST.get('name')
        get_pass1 = request.POST.get('password1')
        get_pass2 = request.POST.get('password2')

        if not get_email  and not get_name  and not get_pass1:
            messages.success(request , 'All fields are mandotry')
            return redirect('src:seller-register')
        
        if User.objects.filter(username=get_email).exists():
            messages.success(request , 'Email Alreday Exist')
            return redirect('src:seller-register')

        if get_pass1 != get_pass2 :
            messages.success(request , 'password did not matched')
            return redirect('src:seller-register')    

        get_user=User.objects.create(username=get_email)
        get_user.set_password(get_pass1)
        get_user.save()

        seller.objects.create(
            user=get_user ,
            name= get_name
        )
        user = authenticate(username=get_email , password=get_pass1)
        dj_login(request , user)
        messages.success(request , 'Account created successfully')
        return redirect('src:home')


    return render(request , 'seller-register.html')

def customer_register(request):
    if request.POST:
        get_email = request.POST.get('username')
        get_name = request.POST.get('name')
        get_phone = request.POST.get('phone')
        get_price = request.POST.get('price')
        get_pass1 = request.POST.get('password1')
        get_pass2 = request.POST.get('password2')

        if not get_email  and not get_name  and not get_pass1:
            messages.success(request , 'All fields are mandotry')
            return redirect('src:seller-register')
        
        if User.objects.filter(username=get_email).exists():
            messages.success(request , 'Email Alreday Exist')
            return redirect('src:seller-register')


        if get_pass1 != get_pass2 :
            messages.success(request , 'password did not matched')
            return redirect('src:seller-register')    

        get_user=User.objects.create(username=get_email)
        get_user.set_password(get_pass1)
        get_user.save()

        customer.objects.create(
            user=get_user ,
            name= get_name ,
            phone = get_phone ,
            price_range = get_price 

        )
        user = authenticate(username=get_email , password=get_pass1)
        dj_login(request , user)
        messages.success(request , 'Account created successfully')
        return redirect('src:home')
    
    return render(request , 'customer-register.html')




def user_logout(request):
    if request.user.is_authenticated:
        deauth(request)
    messages.success(request , "you are logout successfully")
    return redirect('src:home')


def seller_dashboard(request):
    if request.user.is_authenticated:
        get_user = seller.objects.filter(user=request.user).first()
        if get_user:
            all_yachtes=yacht_details.objects.filter(seller_id = get_user)
            return render(request , 'seller-dash.html' , {'yachtes':all_yachtes})
        else:
            messages.success(request , 'You are not a seller ')
            return redirect('src:home')
    else:
        messages.success(request , 'Login First')  
        return redirect('src:login')  

def add_yacht(request):
    if request.user.is_authenticated:
        get_user = seller.objects.filter(user=request.user).first()
        if get_user:
            if request.POST:
                form=yacht_detailsForm(request.POST , request.FILES)
                if form.is_valid():
                    get_f=form.save(commit=False)
                    get_f.seller_id = get_user
                    get_f.save()
                    messages.success(request , "Yacht Added Successfully")
                    return redirect('src:seller-dashboard')
            return render(request , 'add-yacht.html')
        else:
            messages.success(request , 'You are not a seller ')
            return redirect('src:home')
    else:
        messages.success(request , 'Login First')  
        return redirect('src:login')  

def yacht_form(request , pk):
    if request.user.is_authenticated:
        get_user = customer.objects.filter(user=request.user).first()
        if get_user:
            get_yacht = yacht_details.objects.filter(id=pk).first()  
            if request.POST:
                get_weeks = request.POST.get('rent_weeks')
                if not get_weeks:
                    messages.success(request , 'Plaese enter weeks first')
                    return redirect('src:yacht-form' , get_yacht.id)
                
                yacht_id=yacht_details.objects.filter(id=request.POST.get('yacht')).first()
                if book_yatch.objects.filter(yacht_details_id=yacht_id , customer_id=get_user).exists():
                    messages.success(request , 'You have alredy booked this yacht')
                    return redirect('src:yacht-form' , get_yacht.id)
                
                book_yatch.objects.create(
                            yacht_details_id = yacht_id ,
                            customer_id = get_user ,
                            rent_weeks = get_weeks ,
                            price = int( int(get_weeks)* yacht_id.rent_price  )
                )
                message_name="New Booking created"
                meassage_email= get_user.user.username   
                fullmessage="Someone created order for your yacht"
                data={
                    'name':message_name ,
                    'email': meassage_email ,
                    'content':fullmessage ,
                    'phone': get_user.phone 
                }
                html = render_to_string("cont.html" , data)
                send_mail(
                    message_name, 
                    fullmessage ,
                    meassage_email,
                    ['mawazid1051@gmail.com'],
                    html_message=html ,
                    fail_silently=False,
                )
                
                send_mail(
                    message_name, 
                    fullmessage ,
                    meassage_email,
                    ['mawazid1051@gmail.com'],
                    fail_silently=False,
                )
                messages.success(request , "Yacht Booked Successfully")
                return redirect('src:home')  
            return render(request , 'yacht-form.html' , {'i':get_yacht})
        
        else:
            messages.success(request , 'You are not a customer ')
            return redirect('src:home')
    else:
        messages.success(request , 'Login First')  
        return redirect('src:login')  
    

def booked_yacht(request):
    if request.user.is_authenticated:
        get_user = seller.objects.filter(user=request.user).first()
        if get_user:
            books=book_yatch.objects.filter(yacht_details_id__seller_id=get_user)
            return render(request , 'booked-yacht.html' , {'books':books})
        else:
            messages.success(request , 'You are not a seller ')
            return redirect('src:home')
    else:
        messages.success(request , 'Login First')  
        return redirect('src:login')  


def customer_profile(request):
    if request.user.is_authenticated:
        get_user = customer.objects.filter(user=request.user).first()
        if get_user:
            bookings=book_yatch.objects.filter(customer_id=get_user)
            return render(request , 'customer-profile.html' , {'customer':get_user ,'bookings':bookings })
        
        else:
            messages.success(request , 'You are not a customer ')
            return redirect('src:home')
    else:
        messages.success(request , 'Login First')  
        return redirect('src:login')  


   

src/templates/add-yacht.html
{% extends 'base.html' %}
{% block content %}


<div class="row justify-content-center mt-5">
    <div class="col-md-5 shadow p-3 mb-5">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h5 class="text-center card-title-bg">Add Yacht Details</h5>
            <hr>     
            <!-- yacht_type -->
            <div class="mb-3">
            <label class="form-label">Yacht Type</label>
              <select name="yacht_type" class="form-select">
                <option value="Sailing Yacht">Sailing Yacht</option>
                <option value="Motor Yacht">Motor Yacht</option>
                <option value="Gulet Yacht">Gulet Yacht</option>
                <option value="Open Yacht">Open Yacht, Cruiser, Cabin Cruiser, Express Cruiser</option>
                <option value="Luxury Yacht">Luxury Yacht</option>
                <option value="Sports Yacht">Sports Yacht</option>
                <option value="Catamaran Yacht">Catamaran Yacht</option>
              </select>
            </div>
            <!-- yacht_sizes -->
            <div class="mb-3">
                <label class="form-label">Yacht  Sizes</label>
                <select name="yacht_sizes" class="form-select">
                    <option value="Superyachts-24">Superyachts 24 Meters</option>
                    <option value="Megayachts-80">Megayachts  80 Meters</option>
                  </select>
            </div>

            <!-- yacht_style_categories -->
            <div class="mb-3">
                <label class="form-label">Yacht Style Categories</label>
                <select name="yacht_style_categories" class="form-select">
                    <option value="Sedan">Sedan</option>
                    <option value="Flybridge">Flybridge</option>
                    <option value="Flybridge">Flybridge</option>
                    <option value="Daybridge">Daybridge</option>
                    <option value="Open or Enclosed">Open or Enclosed</option>
                    <option value="Downeast Style">Downeast Style</option>
                    <option value="Pilothouse">Pilothouse</option>
                    <option value="Sky Lounge">Sky Lounge</option>
                    <option value="Cockpit Motor Yacht">Cockpit Motor Yacht</option>
                    <option value="Sportfish or Sport Fishing Yacht">Sportfish or Sport Fishing Yacht</option>
                    <option value="Convertible">Convertible</option>
                    <option value="SUV">SUV</option>
                    <option value="Tri-Decks">Tri-Decks</option>
                    <option value="Expedition Yachts">Expedition Yachts</option>
                  </select>
            </div>
            <!-- rent_price -->
            <div class="mb-3">
                <label class="form-label">Rent</label>
                <input type="text" name="rent_price" class="form-control">
            </div>
            <!-- yacht_image -->
            <div class="mb-3">
                <label class="form-label">Yacht Image</label>
                <input type="file" name="yacht_image" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Submit</button>
          </form>
    </div>
</div>




{% endblock %}

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" sizes="32x32 48x48" href="../../media/Yacht Images/yatch.png">
    <title>Sailaway </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'src/static/styles/base.css' %}">  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <style>
      .bg-navbar, btn-bg {
    /* background: #88D7C2; */
    background: rgb(89,190,152);
background: linear-gradient(90deg, rgba(89,190,152,1) 6%, rgba(89,190,152,1) 13%, rgba(136,215,194,1) 50%, rgba(254,254,254,1) 96%);
}

.btn-bg{
    color: #FFF;
    background-color: #59BE98;
    border: 1px solid #59BE98;
}
.btn-bg:hover{
    color: #59BE98;
    background-color: #FFF;
    border: 1px solid #59BE98;
}
.search-btn-bg{
    background-color: #59BE98;
    border-color: #59BE98;
}
.search-btn-bg:hover{
    color: #59BE98 !important;
    background-color: #fff !important;
    border-color: #59BE98 !important;
}
.text-primary-bg{
    color: #88D7C2;
}

.card-title-bg{
    color: #59BE98;
}

.border-success-bg{
    border-color:  #88D7C2;
}
    </style>
    <nav class="navbar navbar-expand-lg bg-navbar">
        <div class="container-fluid">
          <a class="navbar-brand text-white" href="/"><img src="../../media/Yacht Images/Logo.png"/> &nbsp Sailaway</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
             
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="/">Home</a>
              </li>
              {% if request.user.is_authenticated %}
              {% if seller %}
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="{% url 'src:seller-dashboard'%}">Dashboard</a>
              </li>
              {% endif %}
              {% if customer %}
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="{% url 'src:customer-profile'%}">Profile</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="">{{user.username}}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="{% url 'src:logout' %}">Logout</a>
              </li>
              {% else %}
              <!-- register -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Register
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'src:seller-register'%}">Register as Seller</a></li>
                  <li><a class="dropdown-item" href="{% url 'src:customer-register'%}">Register as Customer</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'src:login' %}">Login</a></li>
                </ul>
              </li>
              
             <!-- login  -->
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="{% url 'src:login' %}">Login</a>
              </li>
              {% endif %}
              
             
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn text-white search-btn-bg" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

</head>
  <body>
    <div class="container">
      <!-- DJANGO MESSAGES -->
          {% for msg in messages %}
          <div class="alert container alert-warning alert-dismissible fade show" id="django_msg" role="alert">
              {{msg}}
              
          </div>
        {% endfor %} 
        <!-- END MESSAGES       -->

        <script>
          setTimeout(function() {
              if ($("#django_msg").length > 0) {
                  $("#django_msg").remove();
              }
          }, 5000);
        </script> 

        {% block content %}

        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/booked-yacht.html
{% extends 'base.html' %}
{% block content %}





<div class="row justify-content-center mt-5">
    <div class="col-md-4">
      
        <div class="card" style="width: 18rem;">
            <div class="card-header">
              Featured
            </div>
            <ul class="list-group list-group-flush" >
                <a href="{% url 'src:seller-dashboard'%}">
                <li class="list-group-item" id="dash_ul">  Added Yacht</li>
                </a>
                
                <a href="{% url 'src:add-yacht'%}">
                <li class="list-group-item" id="dash_ul">  Add Yacht </li>
                </a>

                <a href="{% url 'src:booked-yacht'%}">
                  <li class="list-group-item" id="dash_ul">  Booked Yacht </li>
                </a>

            </ul>
          </div>
        
    </div>
    
    <div class="col-md-8 mb-5">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            
            {% for i in books %}
            
            <div class="col">
              <div class="card">
                <img src="{{i.yacht_details_id.yacht_image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                  
                  <h5 class="card-title">Rent Price : {{i.price}}</h5>
                  <h5 class="card-title">Rent Weeks : {{i.rent_weeks}}</h5>
                  <h5 class="card-title">Customer Name: {{i.customer_id.name}}</h5>                  
                  <h5 class="card-title">Customer Email: <span class="text-primary-bg"> 
                    {{i.customer_id.user.username}}
                  </span> </h5>                  
                </div>
              </div>
            </div>
           {% empty %}
            No Booked Yacht Yet
           {% endfor %}
          
          </div>
    </div>
</div>




{% endblock %}

src/templates/cont.html
<h2>Conatct Form </h2>

<p><b>Name</b>{{name}}</p>
<p><b>Email</b>{{email}}</p>
<p><b>Content</b>{{content}}</p>
<p><b>Contact NO:</b>{{phone}} </p>

src/templates/customer-profile.html
{% extends 'base.html' %}
{% block content %}





<div class="row justify-content-center mt-5">
    <div class="col-md-4">
      
        <div class="card" >
            <div class="card-header">
              Personal Details
              <h6 class="fw-bold text-success">{{request.user}}</h6>
            </div>
            <ul class="list-group list-group-flush" >
                
                <li class="list-group-item" id="dash_ul"> <span class="fw-bold">Name </span>     :{{customer.name}}</li>       
                <li class="list-group-item" id="dash_ul"> <span class="fw-bold">Phone </span>     :{{customer.phone}} </li>
                <li class="list-group-item" id="dash_ul"> <span class="fw-bold">Price Range </span>     :{{customer.price_range}} </li>
             

            </ul>
          </div>
        
    </div>
    
    <div class="col-md-8 p-3 mb-5">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            
            {% for i in bookings %}
            <div class="col">
              <div class="card">
                <img src="{{i.yacht_details_id.yacht_image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Rent Price : {{i.price}}</h5>
                    <p class="card-text">category : {{i.yacht_details_id.yacht_style_categories}}</p>
                  <h5 class="card-title">yacht-type :{{i.yacht_details_id.yacht_type}}</h5>
                  <p class="card-text">weeks : {{i.rent_weeks}} </p>
                </div>
              </div>
            </div>
           {% endfor %}
          
          </div>
    </div>
</div>




{% endblock %}

src/templates/customer-register.html
{% extends 'base.html' %}
{% block content %}


<div class="row justify-content-center mt-5">
    <div class="col-md-5 shadow p-3 mb-5">
        <form method="POST">
            {% csrf_token %}
            <h5 class="text-center card-title-bg">Customer Registration</h5>
            <hr>     
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Email address</label>
              <input type="email" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
              <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Name</label>
                <input type="text" name="name" class="form-control" id="exampleInputPassword1">
            </div>

            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Phone</label>
                <input type="text" name="phone" class="form-control" id="exampleInputPassword1">
            </div>
            
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Price Range</label>
                <select name="price" class="form-select">
                    <option value="500000">5,00000+</option>
                    <option value="1000000">10,00000+</option>
                    <option value="1500000">15,00000+</option>
                    <option value="2000000">20,00000+</option>
                  </select>
            </div>
            
            
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" name="password1" class="form-control" id="exampleInputPassword1">
            </div>
            
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Confirm Password</label>
                <input type="password" name="password2" class="form-control" id="exampleInputPassword1">
            </div>        
            <button type="submit" class="btn btn-success">Submit</button>
          </form>
    </div>
</div>




{% endblock %}

src/templates/home.html
{% extends 'base.html' %}
{% block content %}


<div class="row justify-content-center mb-5">

    <div class="row row-cols-1 row-cols-md-2 g-4">
            
        {% for i in yachtes %}
        <div class="col">
          <div class="card shadow">
            <img src="{{i.yacht_image.url}}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title card-title-bg">{{i.yacht_type}}</h5>
              <h5class="card-title">Rent Price : {{i.rent_price}}</h5>
              <p class="card-text">Category : {{i.yacht_style_categories}}</p>
              <p class="card-text">Size : {{i.yacht_sizes}} Meters</p>
            </div>
            {% if customer %}
            <div class="card-footer bg-transparent border-success-bg">
              <a class="btn btn-success btn-bg" href="{% url 'src:yacht-form' i.id%}" role="button">Book Now</a>
            </div>
            {% endif %}
          </div>
        </div>
       
       {% endfor %}
      

</div>





{% endblock %}

src/templates/login.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="row justify-content-center mt-5">
    <div class="col-md-5 shadow p-3 mb-5">
        <form method="POST">
            {% csrf_token %}
            <h5 class="text-center card-title-bg">Login</h5>
            <hr>     
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Email address</label>
              <input type="email" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
              
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" name="password1" class="form-control" id="exampleInputPassword1">
            </div>
              
            <button type="submit" class="btn btn-bg">Submit</button>
          </form>
    </div>
</div>




{% endblock %}

src/templates/seller-dash.html
{% extends 'base.html' %}
{% block content %}





<div class="row justify-content-center mt-5">
    <div class="col-md-4">
      
        <div class="card" style="width: 18rem;">
            <div class="card-header">
              Featured
            </div>
            <ul class="list-group list-group-flush" >
                <a href="{% url 'src:seller-dashboard'%}">
                <li class="list-group-item" id="dash_ul">  Added Yacht</li>
                </a>
                
                <a href="{% url 'src:add-yacht'%}">
                <li class="list-group-item" id="dash_ul">  Add Yacht </li>
                </a>

                <a href="{% url 'src:booked-yacht'%}">
                  <li class="list-group-item" id="dash_ul">  Booked Yacht </li>
                </a>

            </ul>
          </div>
        
    </div>
    
    <div class="col-md-8 mb-5">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            
            {% for i in yachtes %}
            <div class="col">
              <div class="card">
                <img src="{{i.yacht_image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title card-title-bg">{{i.yacht_type}}</h5>
                  <h5class="card-title">Rent Price : {{i.rent_price}}</h5>
                  <p class="card-text">category : {{i.yacht_style_categories}}</p>
                  <p class="card-text">size : {{i.yacht_sizes}} Meters</p>
                </div>
              </div>
            </div>
           {% endfor %}
          
          </div>
    </div>
</div>




{% endblock %}